name: radioplaylist
channels:
  - defaults
dependencies:
  - pandas=1.5.*
  - beautifulsoup4=4.11.*
  - ipykernel=6.19.*
  - requests=2.28.*
  - html5lib=1.1
  - matplotlib=3.6.*
  - pip=22.3.1
  - pip:
    - git+https://github.com/SjoerdCor/micplot